CREATE TABLE filme (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	descricao TEXT NOT NULL,
	disponivel BOOLEAN DEFAULT true,
	categoria VARCHAR(100) NOT NULL,
	responsavel VARCHAR(100),
	data_retirada DATE,

	CONSTRAINT ck_filme_categoria CHECK (categoria IN ('BRONZE', 'PRATA', 'OURO'))
);
