INSERT INTO filme (titulo, descricao, categoria) VALUES
('Harry Potter', 'Harry Potter é um jovem comum de 11 anos até que recebe uma carta para estudar na Escola de Magia e Bruxaria de Hogwarts, onde ele descobre ser, na verdade, um bruxo. Nela, o garoto conquista a amizade de Hagrid, além de Hermione e Ron. No entanto, ele descobre ter um grande inimigo, o terrível Voldemort.', 'OURO'),
('Senhor dos Anéis', 'O hobbit, Frodo, recebe a missão de salvar a Terra-Média do Senhor do Escuro, conhecido como Sauron. Na sua jornada, ele precisa destruir o Um Anel na Montanha da Perdição e, para isso, conta com a ajuda de oito companheiros que juntos formam a Sociedade do Anel', 'PRATA'),
('Clube da Luta', 'Clube da Luta é uma reflexão crítica acerca da sociedade de consumo na qual vivemos e os efeitos que ela provoca nos indivíduos. O filme começa nos mostrando várias marcas famosas e o modo como o protagonista e os demais consomem esses produtos com o objetivo de preencher um vazio interior.', 'OURO'),
('Jogo da imitação', 'O filme “O Jogo da Imitação” relata a história de Alan Turing, que foi um matemático, cientista e também o criador da Máquina de Turing, invenção que servia para decodificação de mensagens criptografadas.', 'OURO'),
('Star Wars I', 'Quando a maquiavélica Federação Comercial planeja invadir o pacífico planeta Naboo, o guerreiro Jedi Qui-Gon Jinn e seu aprendiz Obi-Wan Kenobi embarcam em uma aventura para tentar salvar o planeta. Viajam com eles a jovem Rainha Amidala, que é visada pela Federação pois querem forçá-la a assinar um tratado político.', 'OURO'),
('Star Wars II', 'A história se passa 22 anos antes da explosão da primeira Estrela da Morte. Dez anos se passaram após a invasão de Naboo pela Federação de Comércio, e a República Galáctica está ameaçada por um movimento separatista organizado pelo ex-Mestre Jedi Conde Dooku.', 'OURO'),
('Star Wars III', 'A história se passa 19 anos antes da explosão da primeira Estrela da Morte, durante as Guerras Clônicas. O filme começa na épica batalha sobre Coruscant, onde os Cavaleiros Jedi Obi-Wan Kenobi e Anakin Skywalker lideram um resgate ao Chanceler Palpatine, cativo dos Separatistas.', 'BRONZE'),
('Star Wars IV', 'Uma Nova Esperança (1977) que Obi-Wan vê seu fim chegar pelas mãos de seu ex-aprendiz Darth Vader. Junto de Luke (Mark Hamill) e Han Solo (Harrison Ford), Obi-Wan invade a nave de Vader a fim de resgatar a princesa Leia (Carrie Fischer).', 'OURO'),
('Star Wars V', 'Três anos após a destruição da Estrela da Morte, a Aliança Rebelde continua fugindo da ameaça do Império Galáctico, que manda sondas espiãs por toda a Galáxia em busca dos rebeldes. Uma das sondas vai para o planeta gelado de Hoth, onde a Aliança Rebelde montou a base Echo.', 'OURO'),
('Star Wars VI', 'A história se passa aproximadamente um ano depois dos eventos de Star Wars Episode V: The Empire Strikes Back. O Império Galático, sob a supervisão militar do impiedoso Darth Vader, começou a construção de uma segunda Estrela da Morte, visando aniquilar a Aliança Rebelde.', 'OURO');